{% set name = "docker-credential-helpers" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/docker-credential-helpers/archive/v{{ version }}.tar.gz
  sha256: bc887a126dc294f5c60d0b2d50481cc9ee330249c482bcedd16607e4d18c98ba

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses
    - pkg-config  # [linux]
  host:
    - glib  # [linux]
    - zlib  # [linux]
    - libsecret  # [linux]

test:
  commands:
    - docker-credential-osxkeychain --help  # [osx]
    - docker-credential-pass --help  # [linux]
    - docker-credential-secretservice --help  # [linux]
    - docker-credential-wincred --help  # [win]

about:
  home: https://github.com/docker/docker-credential-helpers
  license: MIT
  license_file:
    - LICENSE
    - license-files/  # [not linux]
    - license-files_pass/  # [linux]
    - license-files_secretservice/  # [linux]
  summary: Docker CLI plugin for extended build capabilities with BuildKit
  dev_url: https://github.com/docker/docker-credential-helpers

extra:
  recipe-maintainers:
    - danielnachun
